#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
apiVersion: operator.openshift.io/v1
items:
- apiVersion: operator.openshift.io/v1
  kind: IngressController
  metadata:
    name: default
    namespace: openshift-ingress-operator
  spec:
    domain: apps.ClusterName.HostedZoneName
    endpointPublishingStrategy:
      loadBalancer:
        scope: External
      type: HostNetwork
    replicas: 3
    selector: ingresscontroller.operator.openshift.io/deployment-ingresscontroller=default
kind: IngressController
